#ifndef _OS_CONFIG_H
#define _OS_CONFIG_H


#define OS_WORKER_MODULE_MSG_MAX_BYTES	ss 
//#define OS_TRANSPORT_MAX_MTU  500
#define OS_TRANSPORT_MAX_MTU	1500
#define OS_SIP_TRANSPORT_BUFFER_SIZE	60
#define OS_HASH_KEY_MAX_LEN	200
#define SYS_MAX_EPOLL_WAIT_EVENTS	10

#define OS_MAX_FILE_NAME_SIZE	160

#endif
